### PR TITLE
refactor setting scenario colours

### PR DESCRIPTION
**Pull request by fbenke-pik**
When setting scenario colours, rather choose from a predefined set of colours than relying on mip::plotstyle(), because
- plotstyle introduces unforeseeable side effects (see https://github.com/pik-piam/mip/issues/114)
- we do not maintain colours for our scenarios in plotstlye anyways, so we always get the default colours (which will now be defined explicitly im piamPlotComparison)

### CODE REVIEW

**Review by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q — COMMENTED** [review]
Umm.
Would that affect all the plots?  Or just the file reference table?  Because I do not much care about the background colours in the table …

**Comment by fbenke-pik** [comment]
The reference table colours are the same ones used for line plots

**Comment by fbenke-pik** [comment]
Or maybe not? This might not fix the problem after all, if showLinepPlots also retrieves the colours using `plotstyle()`.
Will check ...

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
They all use `plotstyle()`.

**Comment by fbenke-pik** [comment]
Closed, as it does not fix the problem as expected.

**Pull request closed without merging**
